name: build
on:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: eu.gcr.io/clementine-data/mingw-w64

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: clementine-data
          workload_identity_provider: projects/611551928920/locations/global/workloadIdentityPools/github-pool/providers/github

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      # Configure Docker to use gcloud as credential helper
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker eu.gcr.io

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest