name: build
on:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: europe-north1-docker.pkg.dev/clementine-data/mingw-w64

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Docker build
        run: docker build -f windows.Dockerfile -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
